name 'Whatbox-PortageGT'
version '1.0.0'
author 'Whatbox Inc.'
summary 'Package provider for Gentoo that supports use flags, keywords and slots'
license 'GPLv3, MIT, BSD'
project_page 'https://github.com/whatbox/PortageGT'